---
abstract: 'Generate function (and its Rinci metadata) to access table data'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-Gen-AccessTable
requires:
  Data::Clone: 0
  Data::Sah: 0
  Lingua::EN::Numbers: 0
  Lingua::ID::Nums2Words: 0
  Moo: 0
  Perinci::Sub::GetArgs::Argv: 0.13
  Rinci: 1.1.13
  SHARYANTO::Role::I18NMany: 0.17
  Test::More: 0.96
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Perinci-Sub-Gen-AccessTable/
  repository: http://github.com/sharyanto/perl-Perinci-Sub-Gen-AccessTable
version: 0.10
