---
abstract: 'Generate function (and its Rinci metadata) to access table data'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-Gen-AccessTable
requires:
  Data::Clone: 0
  Data::Sah: 0
  Lingua::EN::Numbers: 0
  Lingua::ID::Nums2Words: 0
  Log::Any: 0
  Moo: 0
  Perinci::CmdLine: 0
  Perinci::Object::Metadata: 0
  Perinci::Sub::Gen: 0
  Perinci::Sub::GetArgs::Argv: 0.13
  Perinci::Sub::Util: 0.32
  Rinci: v1.1.13
  SHARYANTO::Role::I18NMany: 0.17
  SHARYANTO::String::Util: 0
  experimental: 0
  perl: 5.010001
resources: {}
version: 0.27
